ALTER TABLE `cape`
    CHANGE COLUMN `description` `description` TEXT NULL COLLATE 'utf8mb4_0900_ai_ci' AFTER `allows_codes`;

INSERT INTO cape (alias, allows_codes, description, display_name, image, updated_at)
VALUES ('15th_anniversary', false,
        'This cape was given to visitors of the 15 Year Anniversary page on Minecraft.net who selected the claim button.',
        '15th Anniversary Cape', 'images/cape/15th_anniversary.png', '2026-01-07 03:51:45'),
       ('cherry_blossom', false,
        'This cape was given to players who voted in the 2023 mob vote, voting for either the crab, penguin, or armadillo, through the Minecraft Launcher or the 2023 Mob Vote Event server on Bedrock Edition.',
        'Cherry Blossom Cape', 'images/cape/cherry_blossom.png', '2026-01-07 03:51:46'),
       ('chinese_translator', false,
        'This cape was given to Powup333, Craft_Lawrence and sjjklh on June 4, 2015 for playing vital roles on the Minecraft translation project in Crowdin in Chinese.',
        'Chinese Translator Cape', 'images/cape/translator.png', '2026-01-07 17:44:13'),
       ('christmas_2010', false,
        '	All players were temporarily shown with this cape during Christmas of 2010. However, it was not added to accounts.',
        'Christmas 2010 Cape', 'images/cape/christmas_2010.png', '2026-01-07 17:44:46'),
       ('classic_mojang', false,
        'This cape was given to employees of Mojang Studios. This design was used from December 20, 2010 to October 7, 2015.',
        'Classic Mojang Cape', 'images/cape/classic_mojang.png', '2026-01-07 03:51:50'),
       ('common', false,
        'cape given to all players who use their Microsoft account to log into Bedrock Edition at any point from May 6, 2025 to May 5, 2026.',
        'Common Cape', 'images/cape/common.png', '2026-01-07 17:35:39'),
       ('copper', true,
        'could be obtained as the final reward of a special three-part community challenge known as "The Copper Cape Quest", which began on September 30, 2025.',
        'Copper Cape', 'images/cape/copper.png', '2026-01-07 03:51:53'),
       ('followers', true,
        'This cape was given to players who participated in the TikTok Minecraft livestream of a partnering content creator.',
        'Follower\'s Cape', 'images/cape/followers.png', '2026-01-07 03:51:56'),
	('founders', false, 'This cape was given to players who claimed it in the Marketplace when it was distributed as a promotion for the Character Creator during MINECON Live 2019.', 'Founders Cape', 'images/cape/founders.png', '2026-01-07 17:41:08'),
	('home', true, 'Code available: could be obtained by watching any Minecraft livestream on Twitch for three minutes', 'Home Cape', 'images/cape/home.png', '2026-01-07 15:49:26'),
	('mcc_15th_year', false, 'This cape is given to players for completing all 15 challenges at the MCC x Minecraft 15th Anniversary Party event server hosted on Bedrock Edition from July 22,
        2024 to August 4, 2024.', 'MCC 15th Year Cape', 'images/cape/mcc_15th_year.png', '2026-01-07 17:40:25'),
	('menace', false, 'receive this cape by redeeming a code,
        which could be obtained by watching any Minecraft livestream on TikTok for three minutes. This could be done between March 18,
        2025 and April 6, 2025.', 'Menace Cape', 'images/cape/menace.png', '2026-01-07 17:35:21'),
	('microsoft_xbox', false, 'This cape was given to Microsoft employees on Minecraft: Xbox 360 Edition with the ability to toggle the cape\'s visibility',
        'Microsoft XBOX Cape', 'images/cape/xbox360.png', '2026-01-07 03:52:01'),
       ('migrator', false,
        'This cape was given to players who have bought Minecraft before December 1, 2020 and migrated their Mojang or legacy account to a Microsoft account, starting on July 9, 2021.',
        'Migrator Cape', 'images/cape/migrator.png', '2026-01-07 17:36:04'),
       ('minecon_2011', false, 'This cape was given to MINECON 2011 attendees via their registered username.',
        'Minecon 2011', 'images/cape/minecon_2011.png', '2026-01-07 17:43:05'),
       ('minecon_2012', false,
        'This cape was given to players who redeemed a link emailed to registered MINECON 2012 attendees.',
        'Minecon 2012', 'images/cape/minecon_2012.png', '2026-01-07 17:43:18'),
       ('minecon_2013', false,
        'This cape was given to players who redeemed a link emailed to registered MINECON 2013 attendees.',
        'Minecon 2013', 'images/cape/minecon_2013.png', '2026-01-07 17:43:15'),
       ('minecon_2015', false,
        'This cape was given to players who redeemed a link emailed to registered MINECON 2015 attendees, provided that they had scanned their ticket at the venue\'s entrance on July 4,
        2015.', 'Minecon 2015', 'images/cape/minecon_2015.png', '2026-01-07 17:43:23'),
	('minecon_2016', false, 'This cape was given to players who redeemed a link emailed to registered MINECON 2016 attendees,
        provided that they had scanned their ticket at the venue\'s entrance on September 24, 2016, similar to MINECON 2015\'s method.', 'Minecon 2016', 'images/cape/minecon_2016.png', '2026-01-07 17:43:27'),
	('minecraft_experience', false, 'Obtainable by visiting Minecraft Experience: Villager Rescue,
        an in-person interactive event.', 'Minecraft Experience Cape', 'images/cape/minecraft_experience.png', '2026-01-07 17:41:13'),
	('moderator', false, 'The Moderator Cape is a cape given to moderators on Mojira,
        the Mojang Bug Tracker.', 'Moderator Cape', 'images/cape/moderator.png', '2026-01-07 17:44:38'),
	('mojang', false, 'This cape was given to employees of Mojang Studios. This design was used from October 7,
        2015 to July 25, 2021.', 'Mojang Cape', 'images/cape/mojang.png', '2026-01-07 03:52:07'),
	('mojang_office', false, 'The Mojang Office Cape is a cape which was obtainable by completing all five daily challenges in the Eerie Mojang Office Party.', 'Mojang Office Cape', 'images/cape/mojang_office.png', '2026-01-07 17:42:32'),
	('mojang_studios', false, 'This cape was given to employees of Mojang Studios. This design has been used since July 25,
        2021. ', 'Mojang Studios Cape', 'images/cape/mojang_studios.png', '2026-01-07 03:52:09'),
	('new_year_2011', false, 'All players were temporarily shown with this cape during New Year\'s Eve of 2011. However, it was not added to accounts.',
        'New Year 2011 Cape', 'images/cape/new_year_2011.png', '2026-01-07 17:44:47'),
       ('pan', false, 'This cape was given to all players in the Character Creator cape page.', 'Pan Cape',
        'images/cape/pan.png', '2026-01-07 03:52:11'),
       ('progress_pride', false,
        'This cape is free and part of Pride 2023 Sale and its collection released on August 1, 2023 at 19:00 CET in Minecraft Bedrock Marketplace.',
        'Progress Pride', 'images/cape/progress_pride.png', '2026-01-07 17:40:46'),
       ('purple_heart', true,
        '	This cape was given to players who participated in the Twitch Minecraft livestream of a partnering content creator for at least 15 minutes, with Drops turned on.',
        'Purple Heart Cape', 'images/cape/purple_heart.png', '2026-01-07 17:35:55'),
       ('realms_mapmaker', false,
        'The Realms MapMaker Cape is a cape given to certain contributors in the Java Realms Content Creator Program.',
        'Realms MapMaker Cape', 'images/cape/realms_mapmaker.png', '2026-01-07 17:42:42'),
       ('scrolls_champion', false,
        'This cape was given to players who earned the Weekly First Place winner badge five times in Scrolls starting on November 7, 2014. During Minecon 2015, the Scrolls Minecon Open was also held for Scrolls\' ingame items and other prizes including the cape in Minecraft.', 'Scrolls Champion Cape', 'images/cape/scrolls_champion.png', '2026-01-07 03:52:20'),
	('translator', false, 'This cape was given to some proofreaders (experienced translators with moderation permissions for their language) on the Minecraft translation project in Crowdin', 'Translator Cape', 'images/cape/translator.png', '2026-01-07 17:44:14'),
	('vanilla', false, 'This cape is being given out to players who bought both Java Edition and Bedrock Edition for Windows before June 6,
        2022 and can be equipped in both editions.', 'Vanilla Cape', 'images/cape/vanilla.png', '2026-01-07 17:36:17'),
	('xbox_1st_birthday', false, 'The Xbox 1st Birthday Cape is a cape that was temporarily shown on all players to celebrate the first anniversary of Xbox 360 Edition.', 'Xbox 1st Birthday Cape', 'images/cape/xbox_1st_birthda.png', '2026-01-07 17:44:48'),
	('yearn', false, 'Was obtained by completing all 6 quests in the A Minecraft Movie Live Event,
        an event server hosted from March 25, 2025 to April 14,
        2025 on Bedrock Edition.', 'Yearn Cape', 'images/cape/yearn.png', '2026-01-07 03:52:24'),
	('zombie_horse', false, 'The Zombie Horse Cape could be obtained as a reward for the "Spear Mayhem" challenge,
        which ran from December 12, 2025 at 16:00 UTC to December 15,
        2025 at 18:00 UTC. The challenge involved killing 5 mobs using a spear in Survival mode in Bedrock Edition during the time period.', 'Zombie Horse Cape', 'images/cape/zombie_horse.png', '2026-01-07 17:35:42');

